"""CStarterError et ses sous-classes.

L'API renvoie ses valeurs et lève ses erreurs, la ligne de commande les affiche.
Importable depuis tout le paquet.
"""


class CStarterError(Exception):
    """Une erreur que CStarter explique à l'utilisateur."""


class ConfigError(CStarterError):
    """Un .cstarter/ illisible ou invalide, ou qui ne correspond pas au disque."""


class ProjectNotFoundError(CStarterError):
    """Aucun dossier .cstarter/ dans le dossier désigné ni au-dessus."""


class UnmarkedFileError(CStarterError):
    """L'écriture écraserait des fichiers sans la marque de CStarter."""

    def __init__(self, paths: list[str]) -> None:
        from cstarter.language import t  # language.py importe errors.py : ici, pas en tête

        super().__init__(t("fichiers existants non générés par CStarter : ", "existing files not generated by CStarter: ") + ", ".join(paths))
        self.paths = paths


class ToolchainError(CStarterError):
    """Un outil externe manque ou échoue : vswhere, MSBuild, CMake."""


class PackageError(CStarterError):
    """Le cache de dépendances : entrée absente ou déjà là, téléchargement, archive, recette."""


class NotARepositoryError(CStarterError):
    """Le projet n'est dans aucun dépôt git : init en crée un."""
